/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package principal;

import static java.lang.System.exit;
import tela.*;

/**
 *
 * @author User
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbt_inserirC = new javax.swing.JButton();
        jbt_inserirV = new javax.swing.JButton();
        jbt_Vincular = new javax.swing.JButton();
        jbt_buscar = new javax.swing.JButton();
        jbt_atualizar = new javax.swing.JButton();
        jbt_mostraC = new javax.swing.JButton();
        jbt_periodo = new javax.swing.JButton();
        jbt_mostraV = new javax.swing.JButton();
        jbt_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU");

        jbt_inserirC.setText("INSERIR CLIENTE");
        jbt_inserirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirCActionPerformed(evt);
            }
        });

        jbt_inserirV.setText("INSERIR VINHO");
        jbt_inserirV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_inserirVActionPerformed(evt);
            }
        });

        jbt_Vincular.setText("VINCULAR CLIENTE E VINHOS");
        jbt_Vincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_VincularActionPerformed(evt);
            }
        });

        jbt_buscar.setText("BUSCAR VINHOS DE UM CLIENTE");
        jbt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarActionPerformed(evt);
            }
        });

        jbt_atualizar.setText("ATUALIZAR VINHOS CLIENTE");
        jbt_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizarActionPerformed(evt);
            }
        });

        jbt_mostraC.setText("MOSTRAR CLIENTES");
        jbt_mostraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_mostraCActionPerformed(evt);
            }
        });

        jbt_periodo.setText("APRESENTAR PERÍODO");
        jbt_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_periodoActionPerformed(evt);
            }
        });

        jbt_mostraV.setText("MOSTRAR VINHOS");
        jbt_mostraV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_mostraVActionPerformed(evt);
            }
        });

        jbt_sair.setText("SAIR");
        jbt_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_inserirC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Vincular, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jbt_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_periodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jbt_mostraC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_mostraV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_inserirV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jbt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_inserirV, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jbt_inserirC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Vincular, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_mostraC, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jbt_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbt_mostraV, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(jbt_periodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbt_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_inserirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirCActionPerformed
        TelaCliente telacliente = new TelaCliente();
        telacliente.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_inserirCActionPerformed

    private void jbt_inserirVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_inserirVActionPerformed
        TelaVinho telavinho = new TelaVinho();
        telavinho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_inserirVActionPerformed

    private void jbt_VincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_VincularActionPerformed
        TelaVincularVinhos telavincular = new TelaVincularVinhos();
        telavincular.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_jbt_VincularActionPerformed

    private void jbt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarActionPerformed
        TelaMostrar telamostrar = new TelaMostrar();
        telamostrar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_buscarActionPerformed

    private void jbt_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizarActionPerformed
        TelaAtualizarVinho telaattvinho = new TelaAtualizarVinho();
        telaattvinho.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_atualizarActionPerformed

    private void jbt_mostraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_mostraCActionPerformed
        TelaMostraClientes telamostrarC = new TelaMostraClientes();
        telamostrarC.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_mostraCActionPerformed

    private void jbt_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_periodoActionPerformed
        TelaPeriodo telaperiodo = new TelaPeriodo();
        telaperiodo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbt_periodoActionPerformed

    private void jbt_mostraVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_mostraVActionPerformed
        TelaVinhosCad telavinhsocad = new TelaVinhosCad();
        telavinhsocad.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_jbt_mostraVActionPerformed

    private void jbt_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_sairActionPerformed
        exit(0);
    }//GEN-LAST:event_jbt_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbt_Vincular;
    private javax.swing.JButton jbt_atualizar;
    private javax.swing.JButton jbt_buscar;
    private javax.swing.JButton jbt_inserirC;
    private javax.swing.JButton jbt_inserirV;
    private javax.swing.JButton jbt_mostraC;
    private javax.swing.JButton jbt_mostraV;
    private javax.swing.JButton jbt_periodo;
    private javax.swing.JButton jbt_sair;
    // End of variables declaration//GEN-END:variables
}
